name: Package version patch

on:
  pull_request:
    branches:
    - CI

jobs:
  up_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    - name: show branch to merge
      run: echo ${{github.base_ref}}
    # - run: npm version patch && git push