name: Pull Request title checker

on:
  pull_request:
    branches:
    - CI

jobs:
  title-checker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v4
      - uses: dkershner6/get-pull-request-action@v1
        id: get_pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Script for version
        run: . .github/scripts/check_title_pr.sh
        env:
          pr_title: "${{ fromJSON(steps.get_pr.outputs.pr).title }}"

